/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MIJNIint */

#ifndef _Included_MIJNIint
#define _Included_MIJNIint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MIJNIint
 * Method:    getIncremento
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MIJNIint_getIncremento
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
